### ISSUE TITLE
Wrong launching when clicking on UI for IM tool

### ISSUE THREAD

**Issue by bagjunggyu** [linuxmint/mint-19.1-beta#11]
It launches Language(Region & language) when clicking Input Method(한글 입력) in cinnamon-settings.
Whether language is Korean or English it happens all the time.

but, in terminal
$ mintlocale-im
it launches correctly

launching it by clicking it in /usr/share/applications/입력기(input method)
it launches correctly.

launching it(한글 입력) in menu works correctly too.

Can you check the link for Input Method tool in cinnamon-settings?

And added it here
I found that same translated Korean name with Input Method(입력기) in /usr/share/applications/.
it was im-config(입력기).
for this reason,
I switched its(input method – 입력기) translation in mintlocale to 한글 입력  same as in cinnamon(Input Method – 한글 입력) for avoiding confusion with hope of its resolving.
Thank you

**Frequency**
Does the issue happen:
[0] Always
[ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
[0] Cinnamon Edition
[x] MATE Edition
[x] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
[0] Post-install
[0] Live session

**Comment by bagjunggyu** [comment]
It is resolved after the system update now.
Hope it to be same in live session of regular release.
Thank you :)

**Comment by NikoKrause** [comment]
Yes, that was fixed here: https://github.com/linuxmint/mint-19.1-beta/issues/5
