### ISSUE TITLE
cinnamon: 'Modern' layout - Menu and Calendar applets padding missing

### ISSUE THREAD

**Issue by DaveBlack** [linuxmint/mint-19.1-beta#12]
**Describe the bug**
Padding missing either side of the Menu icon. Most noticeable when using 24px or smaller icons on Left panel zone...

Padding also required right side of Calendar applet, currently the time appears at screen edge.

**To Reproduce**
1. Panel settings
2. Left panel zone... select 24px, or smaller
3. Notice 'Show desktop' applet appears too close to Menu, compared with space between 'Show desktop' and GWL

**Expected behavior**
Spacing should (if possible) be proportional

**By comparison**
1. Menu -> Configure
2. Enable 'Use a custom icon and label'
3. Replace "Menu" text with " " (one space)
4. Close configure window, now compare spacing

**Frequency**
Does the issue happen:
[x] Always
[ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
[x] Cinnamon Edition
[ ] MATE Edition
[ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
[x] Post-install
[x] Live session

**Locale:**
LANG=en_GB.UTF-8

**Drivers:**
NVIDIA 390.77

**Additional context**
Would like to take a moment to thank Linux Mint developers, noticed 19.1 beta fixes a long term issue, Mint Menu icon proportions were incorrect (used to appear squashed). Even the smallest of details make a big difference.

**Comment by clefebvre** [comment]
Fixed (partly) by https://github.com/linuxmint/mint-themes/commit/817bae3e629e7a4af70e5f03f2ba801d862b8fb1

**Comment by DaveBlack** [comment]
Thank you for the partial fix.

As a temporary solution, will use modification mentioned above for peoples installs (Use a custom icon and label, replace 'Menu' word with a single space), and adding the Mint logo, which helps provide more uniform icon/spacing.

Compare space between Mint logo, Show desktop, and GWL (not perfect but better).
32px, 24px, and 16px
 ![padding compare](https://user-images.githubusercontent.com/13056699/50047470-cc64a180-00ad-11e9-8d5c-ccd2138a1483.png)

PS: Tried using Spacer applet, but even after editing the configs .json file to allow a size of 0, the gap was still too large.
