### ISSUE TITLE
Steam icon is still broken

### ISSUE THREAD

**Issue by fernandometal** [linuxmint/mint-19.1-beta#13]
Steam tray icon is still broken. Whenever you open steam and the icon is there you can see that its positioning is broken, and when you click it he won't obey the gtk theme, having a grey = with blue highlight theme instead, similar to Windows 98.

**Frequency**
Does the issue happen:
[X] Always
[ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
[X] Cinnamon Edition
[ ] MATE Edition
[ ] Xfce Edition

**Comment by NikoKrause** [comment]
Steam icon looks good here:
![screenshot-cinnamon-2018-12-06-223425](https://user-images.githubusercontent.com/8415124/49613142-232ff400-f9a7-11e8-8de9-fcb4233f852e.png)

If you want steam to integrate more with your theme, you can enable indicator support.

System Settings -> General -> Enable support for indicators (Requires Cinnamon restart)

**Comment by fernandometal** [comment]
That did it. Thanks!
