### ISSUE TITLE
cinnamon: Unable to type in search bar directly when enable hovering menu.

### ISSUE THREAD

**Issue by bagjunggyu** [linuxmint/mint-19.1-beta#15]
**Describe the bug**
Enable Hover on Menu in menu configuration --> Can't type in words directly 

**To Reproduce**
1. Go to 'Menu' and right click
2. Click on 'Configure'
3. Enable Hover on menu
4. Type in search bar in menu --> unable to input words.
5. Click on search bar then available to type in words. 

**Expected behavior**
It should be able to input words as default.

**Frequency**
Does the issue happen:
[0] Always
[ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
[0] Cinnamon Edition
[ ] MATE Edition
[ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
[0] Post-install
[0] Live session

**Comment by NikoKrause** [comment]
Reproduced and fixed. Created pull request. Thanks for pointing this out.

**Comment by ghost** [comment]
Nice ! :)
