### ISSUE TITLE
mint-y-icons: aisleriot and kpat have the same icon

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint-19.1-beta#16]
**Describe the bug**
Two Games (aisleriot Solitare and kpat KPatience Show the Same Mint-Y Icon.

**To Reproduce**
1. Install aisleriot (Solitare) and kpat (KPatience)
2. Check to see Mint-Y Icon theme is selected.
3. Go to Start Menu | Games
4. See that both games have the same icon.
5. Switch to Mint-X Icon theme and check again and see that they are different.

**Expected behavior**
Expected icons to be different in Mint-Y theme as they are in the Mint-X theme.

**Frequency**
Does the issue happen:
[x] Always
[ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
[x] Cinnamon Edition
[ ] MATE Edition
[ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
[x] Post-install
[x] Live session

**Screenshots**

**Locale:**
LANG=en_US.UTF-8
LANGUAGE=en_US

**Drivers:**
N/A

**Additional context**
N/A

**Comment by NikoKrause** [comment]
See https://github.com/linuxmint/mint-19.1-beta/issues/17 for an explanation.
