### ISSUE TITLE
mint-y-icons: 2 icons miss background art at 24 and 24@2x

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint-19.1-beta#2]
**Describe the bug**
All of the Mint-Y icon sets are missing the background art for for folder-documents.png and folder-music.png at the following sets:

/usr/share/icons/Mint-Y/places/24
/usr/share/icons/Mint-Y/places/24@2x

**To Reproduce**
    Go to Nemo in any Mint-Y theme.
    Click on Icon View
    Click on List View
    Click on Compact View
    See that Documents and Music Icons are missing their background art.

**Expected behavior**
Expected to see the same art on all icon sizes.

**Frequency**
Does the issue happen:
[X ] Always
[ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
[X ] Cinnamon Edition
[ ] MATE Edition
[ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
[X ] Post-install
[X ] Live session

**Screenshots**
![screenshot-nemo](https://user-images.githubusercontent.com/45599505/49450396-e4354f00-f7aa-11e8-8930-dae57b864654.jpg)

**Comment by NikoKrause** [comment]
Good catch. Those icons are missing indeed.

**Comment by JosephMcc** [comment]
Wow, I never noticed that and have been using them for awhile. I'll take a look

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mint-y-icons/commit/b7843ab47395d3b062ff65fda266187931ad4894
