### ISSUE TITLE
mint-x-icons: Wrong Speaker Icon in Mate Panel

### ISSUE THREAD

**Issue by Jildridge** [linuxmint/mint-19.1-beta#21]
**Describe the bug**
When changing the appearance in Mint Mate 19.1 back from a Mint-Y Theme to any Mint-X theme the speaker icon in the panel becomes strange (an icon that represents a screen or sth. of the like.)

**To Reproduce**
Switch from Mint-Y to Mint-X results in this small 'problem'
Switching back to Mint-Y makes the speaker icon look as it is supposed to be.

**Frequency**
Does the issue happen:
[X ] Always (Mint Mate 19.1 but not in 19.0)
[ ] Randomly
Edit: The problem does not occur when using the proprietary nvidia 340 driver instead of the x.org x.server driver.

**Edition (Desktop environment):**
In which edition is this happening?
[ X] MATE Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
[ ] Post-install
[X ] Live session

**Comment by clefebvre** [comment]
Fixed in mate-media 1.20.0-1ubuntu1mint3.
