### ISSUE TITLE
ubiquity: Kabyle is not available in the language list

### ISSUE THREAD

**Issue by S-Amiri** [linuxmint/mint-19.1-beta#22]
I come to try the Beta 19.1 version after the instalation I installed the language Kabyle and the system perfectly displays the Kabyle.
Unfortunately, we do not find Kabyle at the start of the installation, Kabyle is not available in the step of the installation (live installation)

**Comment by clefebvre** [comment]
Hi,

You mean it's not in the list of languages within the installer?
How do you say "Kabyle" in Kabyle?

The locale is kab.

**Comment by clefebvre** [comment]
It seems to be missing in https://github.com/linuxmint/ubiquity/blob/master/d-i/source/localechooser/languagelist

**Comment by clefebvre** [comment]
It's missing upstream as well. @S-Amiri let me know how you say "Kabyle" in Kabyle, and I can try and test a fix for this.

**Comment by NikoKrause** [comment]
native name: `Taqbaylit`

https://en.wikipedia.org/wiki/Kabyle_language

**Comment by Azwaw1** [comment]
Yes, the native name of kabyle is : Taqbaylit

**Comment by Azwaw1** [comment]
@clefebvre
 the native name of kabyle is : Taqbaylit

**Comment by MohammedBelkacem** [comment]
Please, would you like refer to Ethnologue: https://www.ethnologue.com/language/kab

Kabyle is present on ISO 639-2 alpha 3

on CLDR: http://st.unicode.org/cldr-apps/v#/kab/Alphabetic_Information/
________

**Comment by MohammedBelkacem** [comment]
@S-Amiri how about the keyboard, shall we submit the one the community is using on windows (the one inherited from Frecnh Azerty?). I think we shall keep it as most people is using that Keyboard.

**Comment by Azwaw1** [comment]
@belkacem77 yes, We can keep the one we use on Windows, it is very convenient, or use the keyboard I did for Linux:
https://github.com/S-Amiri/anasiw/

**Comment by clefebvre** [comment]
OK, we can help with this. It won't be complete though.

You need to ask upstream to add proper support as well:

- In Debian, you need to add that kabyle be added to localechooser (that's what we're doing in the next commit).
- In Ubuntu, you need to make sure the next versions of Ubiquity come with Kabyle translations (this is not the case in Mint).

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintlocale/commit/291dde42e573f7459af63c2ceb85ab7e31ab754e adds support for Kabyle in mintlocale.

**Comment by clefebvre** [comment]
Here's a quick overview of all the PO files involved for a full Ubiquity translation (Ubiquity uses many 3rd party modules from debian-installer): 

```
clem@airtop ~/Sandbox/ubiquity $ find . | grep fr.po
./debian/real-po/fr.po
./debian/imported-po/fr.po
./d-i/source/localechooser/debian/po/fr.po
./d-i/source/partman-basicfilesystems/debian/po/fr.po
./d-i/source/user-setup/debian/po/fr.po
./d-i/source/partman-base/debian/po/fr.po
./d-i/source/partman-crypto/debian/po/fr.po
./d-i/source/netcfg/debian/po/fr.po
./d-i/source/tzsetup/debian/po/fr.po
./d-i/source/partman-btrfs/debian/po/fr.po
./d-i/source/partman-ext3/debian/po/fr.po
./d-i/source/partman-auto-lvm/debian/po/fr.po
./d-i/source/base-installer/debian/po/fr.po
./d-i/source/preseed/debian/po/fr.po
./d-i/source/flash-kernel/debian/po/fr.po
./d-i/source/partman-xfs/debian/po/fr.po
./d-i/source/console-setup/debian/po/fr.po
./d-i/source/partman-auto-crypto/debian/po/fr.po
./d-i/source/partman-auto/debian/po/fr.po
./d-i/source/hw-detect/debian/po/fr.po
./d-i/source/choose-mirror/debian/po/fr.po
./d-i/source/partman-efi/debian/po/fr.po
./d-i/source/partman-target/debian/po/fr.po
./d-i/source/partman-basicmethods/debian/po/fr.po
./d-i/source/partman-jfs/debian/po/fr.po
./d-i/source/debian-installer-utils/debian/po/fr.po
./d-i/source/clock-setup/debian/po/fr.po
./d-i/source/partman-lvm/debian/po/fr.po
./d-i/source/partman-partitioning/debian/po/fr.po
./d-i/source/grub-installer/debian/po/fr.po
./d-i/source/apt-setup/debian/po/fr.po
./po/fr.po

```

**Comment by clefebvre** [comment]
https://github.com/linuxmint/ubiquity/commit/00e4f7792aa8204968c0ac363587411327353e81 adds Kabyle to the list in the installer.

**Comment by clefebvre** [comment]
So, the installer will still be in English, and the default keyboard will still be en_US, but with these changes you should be able to select "Taqbaylit" in the installer, and end up with a localized environment in kab_DZ.

**Comment by Azwaw1** [comment]
@clefebvre
ok, thank you so much, it is a first solution, People will install LinuxMint mint with an English installer but the essential they will have the kabyle interface in the end, so to properly fix the problem we will start to Localizer Ubuntu itself

**Comment by clefebvre** [comment]
PS: The installation slideshow will be in Kabyle.

**Comment by clefebvre** [comment]
OK, just tested and it's all good.

![image](https://user-images.githubusercontent.com/1138515/49822827-1da32700-fd76-11e8-95e1-2686697a88cf.png)
![image](https://user-images.githubusercontent.com/1138515/49822914-4fb48900-fd76-11e8-9d54-2e1d778b431a.png)

**Comment by Azwaw1** [comment]
@clefebvre
Great, thank you
