### ISSUE TITLE
cinnamon: gwl: Drag-and-drop hovering to access a secondary window in a group not working

### ISSUE THREAD

**Issue by Piiit** [linuxmint/mint-19.1-beta#23]
**Describe the bug**
If I want to drag-and-drop a file to a currently not focused window, I hold the mouse button down and hover over a group inside the GWL applet, the hovered application gets the focus and I can move on to the window itself and release the mouse button. In contrast, when I want to access the second (or any subsequent) window in that group I cannot access it with hovering.

**To Reproduce**
1. Open Libreoffice writer 2 times (GWL must be set to show grouped apps)
2. Open Nemo, choose a file (compatible with writer) and click it (hold the mouse button down)
3. Move it to the GWL applet over the writer group
4. Try to access the second writer window in that group (which is not possible)

**Expected behavior**
I would expect, that the window previews open on hover and that I can choose the second (or third, ...) window in that list. On hover of a preview, that window should get the focus and I can drop the dragged file there.

**Frequency**
Does the issue happen:
[x] Always
[ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
[x] Cinnamon Edition
[ ] MATE Edition
[ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
[ ] Post-install
[x] Live session

**Screenshots**

**Locale:**
Paste the output of `locale`.

**Drivers:**
Paste the output of `inxi -Gxx`.

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**

**Comment by jaszhix** [comment]
This is a known issue for grouped apps previously tracked at https://github.com/jaszhix/icingtaskmanager/issues/140. This will likely not get fixed in time for 19.1.

**Comment by Piiit** [comment]
@jaszhix OK, will "native" applets get updates before LM 19.2? Or do they get them only within a new cinnamon release?

**Comment by jaszhix** [comment]
They usually only get updated when Cinnamon does - but I have good news, I've been experimenting and I think I found a way to do it. Will hopefully have a PR up soon.

**Comment by Piiit** [comment]
That are great news. Thx a lot...
Btw, let me know when you are ready for beta testing B-)

**Comment by jaszhix** [comment]
I'm pretty much done with that PR, feel free to check out the branch and test. :) I'll update it if there's any regressions.

**Comment by Piiit** [comment]
@jaszhix I hope I find the time this week

**Comment by Piiit** [comment]
@jaszhix Tested with https://github.com/jaszhix/Cinnamon/commit/1a63e3dbc84cdd7b035787729aa76bb508a5176e. It works!  Thx

Should I close the issue?
