### ISSUE TITLE
Update Manager is not fully translated to pt_BR.

### ISSUE THREAD

**Issue by VaGNaroK** [linuxmint/mint-19.1-beta#25]
**Describe the bug**
after installing the system with all updates and language packs, the update manager still remains in English, "select", "All updates", "Updates"

**To Reproduce**
1. Go to 'update manager'
2. Click on 'select'

**Expected behavior**
...

**Frequency**
Does the issue happen:
- [X] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [X] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Screenshots**
https://postimg.cc/F13fzRCZ

**Comment by NikoKrause** [comment]
https://github.com/linuxmint/mintupdate/commit/857d8aaaf9c30dba45a50a964842fdaac3ad62f8
