### ISSUE TITLE
[i18n-wishlist] Update Translaion for All Edition

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-19.1-beta#27]
This is a wishlist for newly updated translation for those edition.

Cinnamon
Xfce
MATE

I hope that
All of the edition update to newly updated translation before release
Thank you

**Comment by gm10** [comment]
I'm sure your help with missing translations would be welcome: https://linuxmint-translation-guide.readthedocs.io/en/latest/

**Comment by ghost** [comment]
@gm10 Yes, I am leading Linux Mint and Cinnamon Korean transaltion now.
https://translations.launchpad.net/linuxmint/latest/+lang/ko
and Coordinator of MATE, Xfce....and a lot more...

I have checked the translation state of 19.1 and I found that missing translation of Cinnamon and MATE.
for this reason, I want it to be fixed or updated before regular release.
I am sure that Cinnamon will be! but can not sure that MATE would be.
so that I reported it here for MATE and for other language's users. 

I hope that we can meet updated translation in regular release.

**Comment by gm10** [comment]
MATE and Xfce translations are done by their respective teams, I don't think Mint does any work there.

As to the rest, I'd expect Clem to do a translations update before this releases, but if you've got packages that you think have been missed, namely packages that had translations waiting before the beta .iso was created, then it probably cannot hurt to list them here.

**Comment by ghost** [comment]
Any chances to have massive collecting of all Desktop Environment's translation one more time before creating .iso?
In my opinion, I think it would be better for all users.
and also this is my wish.

**Comment by clefebvre** [comment]
Absolutely, this is always planned prior to releases. I'll close this for now as the report isn't necessary.

**Comment by ghost** [comment]
Nice!!!
Thank you
Merry Christmas :)
