### ISSUE TITLE
Application source dont open 

### ISSUE THREAD

**Issue by otavioschwanck** [linuxmint/mint-19.1-beta#28]
**Describe the bug**

**To Reproduce**
1. Open Application Source
2. Put your password

**Expected behavior**
Just dont open.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**
Video:
https://www.dropbox.com/s/llrbgmutcrz359z/bug.mkv?dl=0

**Locale:**
PT-BR

**Drivers:**
Graphics:
  Device-1: Intel HD Graphics 5500 vendor: Dell driver: i915 v: kernel 
  bus ID: 00:02.0 chip ID: 8086:1616 
  Device-2: AMD Topaz XT [Radeon R7 M260/M265 / M340/M360 / M440/M445] 
  driver: amdgpu v: kernel bus ID: 04:00.0 chip ID: 1002:6900 
  Display: x11 server: X.Org 1.19.6 driver: amdgpu,ati,modesetting 
  unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 5500 (Broadwell GT2) 
  v: 4.5 Mesa 18.0.5 compat-v: 3.0 direct render: Yes

**Comment by gm10** [comment]
In a terminal window, please run `mintsources` and post the output (if any).

**Comment by otavioschwanck** [comment]
➜  ~ mintsources 
LSB codename: 'bionic'.
Version of base-files: '19.1.2'.
Your LSB codename isn't a valid Linux Mint codename.
Please check your LSB information with "lsb_release -a".


I've changed lsb_release to install RVM.  Forgot to rollback.  My bad =D
