### ISSUE TITLE
PPAs not receiving GPG keys

### ISSUE THREAD

**Issue by agent193** [linuxmint/mint-19.1-beta#29]
**Describe the bug**
When attempting to add a PPA (either through terminal command or in the GUI), the process encounters an error and is unable to receive the signing key. 

Terminal and GUI both receive a GPG error. I tried this on 3 different PPA's and all of them exhibit the same behavior. These PPA's work without issue in LM 19.0

Example PPAs:
ppa:libreoffice/libreoffice-6-1
ppa:phoerious/keepassxc
ppa:otto-kesselgulasch/gimp

**To Reproduce**
1. Terminal: add ppa with command 'add-apt-repository'
2. GUI: add ppa through Software Sources

**Expected behavior**
PPA is added to software sources and the signing key installed. The PPA does show in the software sources but update manager will give an error due to the missing key.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition (only one tested)
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Comment by gm10** [comment]
Please include the actual errors you are getting. I cannot reproduce this issue at all. 

PS: Regarding connectivity, note that Software Sources doesn't support proxies.

**Comment by smurphos** [comment]
I can't reproduce this either. The keyserver seems a bit slow at the moment - maybe you are having connectivity issues to the key server.

I've successfully added `ppa:phoerious/keepassxc` via Software Sources  and `ppa:teejee2008/ppa` via `sudo apt-add-repository -y` this morning.

**Comment by agent193** [comment]
Here are the full error messages I am getting. No proxy server is being used.

**Error via Software Sources:**
W:GPG error: http://ppa.launchpad.net/phoerious/keepassxc/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 61922AB60068FCD6, E:The repository 'http://ppa.launchpad.net/phoerious/keepassxc/ubuntu bionic InRelease' is not signed.

**Error via Terminal:**
You are about to add the following PPA:
 KeePassXC Password Manager (official upstream PPA)

Note to Xenial users who used keepassxc-beta before: you may need to uninstall/reinstall libsodium18 from the Ubuntu repositories if you are experiencing conflicts with libsodium32. See https://github.com/keepassxreboot/keepassxc/issues/1545#issuecomment-369163954
 More info: https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc
Press Enter to continue or Ctrl+C to cancel

Executing: /tmp/apt-key-gpghome.b2Fl8v9vLf/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys D89C66D0E31FEA2874EBD20561922AB60068FCD6
gpg: keyserver receive failed: Server indicated a failure

**Comment by agent193** [comment]
I manually set DNS servers to Google's public DNS servers 8.8.8.8 and 8.8.4.4 and the keys imported just fine.

**Comment by gm10** [comment]
So the problem was your local DNS server didn't give the correct IP for keyserver.ubuntu.com. It would probably have cleared itself in a little while. Either way, nothing we can do about.
