### ISSUE TITLE
mintwelcome: Traditional View Needs Refinement

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint-19.1-beta#3]
**Describe the bug**
It had been mentioned in Mint Blog October News: "Whether you enjoy the new look or prefer the old one, we want everyone to feel at home in their operating system, so you’ll have the option to embrace the change or to click a button to make Cinnamon look **just like it did before.**"
This is still not happening.

**To Reproduce**
1. Go to Welcome Screen
2. Scroll down to 'Desktop Layout'  
3. Click on 'Traditional'

**Expected behavior**
That this would be closer to the Traditional Cinnamon but it is not quite.

Suggested dconf entries to get closer to that look:
dconf write /org/cinnamon/panel-zone-icon-sizes "'[{"panelId": 1, "left": 22, "center": 22, "right": 22}]'"
dconf write /org/cinnamon/panels-height "['1:25']"
dconf write /org/cinnamon/theme/symbolic-relative-size "0.75"

~/.cinnamon/configs/menu@cinnamon.org *.json file should have the parameter "favbox-min-height" set back to "value": 300.0

**Frequency**
Does the issue happen:
[X ] Always
[ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
[X ] Cinnamon Edition
[ ] MATE Edition
[ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
[X ] Post-install
[X ] Live session

**Screenshots**
See screen shot of proposed changes.
![panel](https://user-images.githubusercontent.com/45599505/49452767-c5858700-f7af-11e8-9835-2a969ced4366.jpg)

**Comment by clefebvre** [comment]
favbox is 300 in 4.0.4+.

**Comment by Harry-W-Haines-III** [comment]
Looking better!  Saw where the default Symbolic icon size adjustment for "traditional" was set to .67 as well.

**Comment by clefebvre** [comment]
Yes, I think the biggest issue (other than the menu) was the symbolic adjustment. The .67 factor is calculated to make them look crisp and adjust them from 24px to 16px by default.

I'd prefer to keep them at 24/27 (it looks just the same as in 19.0) and make them scale by default.
