### ISSUE TITLE
mintupdate: Kernel update module doesn't display installed low-latency kernels

### ISSUE THREAD

**Issue by morton-f** [linuxmint/mint-19.1-beta#31]
The installed low-latency kernels are not represented in the Update Manager **Kernel module** simultaneously with generic kernels. 
Kernel _mintupdate_ module is convenient and unique feature of Linux Mint. As far as I know there is no such standard utility in other popular distributions. Anyway when low-latency kernels are installed, the information provided can be interpreted misleadingly.

Additionally, I hope there is a way to implement installation of **mainline Ubuntul kernels** form kernel.ubuntu.com/~kernel-ppa/mainline/ (may be as an Advanced mode).

Additional context:
[](https://github.com/linuxmint/mintupdate/issues/432)

1. Install low-latency kernel (by any method, for eg from Synaptic)
2. Open Update Manager -> View -> Linux kernels
3. Check that information about the low-latency kernel is absent.

[+] All Editions
[+] Post-install

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintupdate/issues/432, not a release blocker but we'll address it during the cycle.
