### ISSUE TITLE
Print screen key does not work when some application is with the main menu visible.

### ISSUE THREAD

**Issue by antrrax** [linuxmint/mint-19.1-beta#34]
**Describe the bug**
printcreen key does not work when some application is with the main menu visible.

**To Reproduce**
1. open Xed
2. click on the "File" main menu or other main menu item, the menu will be displayed on the screen
3. press the printscreen key while the "File" menu is visible. the screen image is not captured

**Expected behavior**
printscreen key should always work.

**Frequency**
Does the issue happen:
- [x ] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x ] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x ] Post-install
- [ ] Live session

**Locale:**
pt-BR utf-8

**Comment by antrrax** [comment]
<a href="https://ibb.co/t3SFSNp"><img src="https://i.ibb.co/GFXNX1Q/bug00.jpg" alt="bug00" border="0"></a>

**Comment by gm10** [comment]
That's a Gtk limitation (the framework all the Mint desktops are built upon), it catches all keyboard input while a menu is open and won't pass it through, no shortcuts will work in this situation. It's annoying but nothing the Mint guys can do about short of patching Gtk, which they won't do. 

The screenshot tool has a time-delayed mode to work around this (at least I hope it does on Cinnamon as well, I'm not so familiar with that DE).

**Comment by smurphos** [comment]
It does.
