### ISSUE TITLE
pix: same shortcut "Ctrl + P" for two commands

### ISSUE THREAD

**Issue by antrrax** [linuxmint/mint-19.1-beta#35]
**Describe the bug**
in the Pix software. there are two commands with the same keyboard shortcut, print (Ctrl + P) and paste image (Ctrl + P), so I can not use the image paste shortcut.

**To Reproduce**
1. open Pix application
2. Double click on any image. the image display mode will appear.
3. In the main menu "File"> Print, the shortcut is "Ctrl + P" that is OK

4. But in the main menu "Edit"> Paste image, the ALSO shortcut is "Ctrl + P", THIS IS THE ERROR

**Expected behavior**
"Ctl + V" paste image from clipboard

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Locale:**
pt-BR utf-8

**Additional context**
File:
https://github.com/linuxmint/pix/blob/master/extensions/image_viewer/gth-image-viewer-page.c

line 184, ERROR:
N_("Paste Image"), "<<control>control>p",

**Comment by otavioschwanck** [comment]
Here too.  Confirmed.

**Comment by antrrax** [comment]
<a href="https://imgbb.com/"><img src="https://i.ibb.co/fCDGh30/bug.png" alt="bug" border="0"></a>
