### ISSUE TITLE
[Request] Yellow icon themes for Mint-Y (like windows10 yellow folder)

### ISSUE THREAD

**Issue by antrrax** [linuxmint/mint-19.1-beta#36]
I miss a yellow icon theme for the Mint-Y
They could do with a similar shade of yellow the 'Windows 10 folders'

It would be easier for Windows 10 users to migrate to Mint if the Mint-Y theme folders were yellow.

**Edition (Desktop environment):**
In which edition is this happening?
- [x ] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x ] Post-install
- [ ] Live session

**Comment by Acheron17** [comment]
I too, would appreciate having the complimentary set of Mint-Y-Yellow Icons available.

**Comment by clefebvre** [comment]
This will be looked at for 19.2. We're planning to review all Mint-Y tints in the next release.
