### ISSUE TITLE
Applet Drives Removable on the taskbar, does not display notification message

### ISSUE THREAD

**Issue by antrrax** [linuxmint/mint-19.1-beta#37]
**Describe the bug**
Applet Drives Removable on the taskbar, does not display notification message when we eject a usb flashdrive.
However in Nemo when we eject a usb flashdrive the notification appears.

**To Reproduce**
1. to put a usb flashdrive on the pc.
2. Go to 'removable drives' on task bar
3. Click on 'eject usb flashdrive'

**Expected behavior**
display notification that the usb flashdrive can be safely removed, like Nemo.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Locale:**
pt-BR utf-8

**Comment by antrrax** [comment]
<a href="https://ibb.co/w7xqvV8"><img src="https://i.ibb.co/jz1Ypmq/bug3.png" alt="bug3" border="0"></a>

**Comment by NikoKrause** [comment]
This is an old bug: https://github.com/linuxmint/Cinnamon/issues/5377
