### ISSUE TITLE
cinnamon: Titlebar close button sometimes doesn't change colour to match Mint-Y theme in Mint 19.1 Beta (Cinnamon 4)

### ISSUE THREAD

**Issue by PlanetLinux98** [linuxmint/mint-19.1-beta#38]
* Cinnamon version 4.0
* Mint 19.1 Beta
* 64-bit
* Pre- and post-install
* Intel HD 620 integrated graphics (at least in my case) 

**Description**
When changing the control theme and icon theme to the various Mint-Y colours in Mint 19.1 beta, the close button in the titlebar (which is supposed to match the theme highlight colour) does not change most of the time, usually staying the default green.

**Steps to reproduce**
Open Settings > Themes and make sure the Mint-Y or Mint-Y Dark Window Title theme is selected then choose a different-coloured Mint-Y theme for the main window content.

**Expected behaviour**
More often than not, the close button in the titlebar retains its green colour instead of changing to match the rest of the theme.

**Comment by clefebvre** [comment]
That color in metacity-3 isn't hardcoded, it's defined by the GTK theme. We could add a listener in muffin but I'm not sure it's worth doing right now, especially as we're moving away from metacity themes and it would be removed in 4.2.
