### ISSUE TITLE
can not enable numlock in login window

### ISSUE THREAD

**Issue by antrrax** [linuxmint/mint-19.1-beta#39]
**Describe the bug**
The button, to turn on or off, the numlock in the login window is not enabled.

**To Reproduce**
1. In System Settings> Administration> Login Window> Settings
2. The "Activate numlock" option is disabled, it is not allowed to turn on or off this button.

**Expected behavior**
The button to turn on or off numlock in the login window should be enabled

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**

**Locale:**
pt-BR utf-8

**Comment by gm10** [comment]
Not a bug. Hover your mouse over the greyed out option, the tooltip will explain it.
