### ISSUE TITLE
Cinnamon Panel Progress Indicator does not match selected theme

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint-19.1-beta#4]
**Describe the bug**
During the Mint 19 Beta cycle there was an issue in postponed concerning the color of the Cinnamon Panel Progress Indicator.  It was always green instead of matching the theme.  In Cinnamon 4 **for the default Theme / Desktop / Cinnamon** it 'looks' that issue was not 'fixed'.  It does work for the other Mint-X and Mint-Y desktops.

**To Reproduce**
1. Go to 'Copy files, download ...'
2. See the  Cinnamon Panel Progress Indicator is green and does not match the theme.

**Expected behavior**
Expected Cinnamon Panel Progress Indicator to match the theme.

**Frequency**
Does the issue happen:
[X] Always
[ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
[X] Cinnamon Edition
[ ] MATE Edition
[ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
[X] Post-install
[X] Live session

**Screenshots**

**Locale:**
LANG=en_US.UTF-8
LANGUAGE=en_US

**Drivers:**
Graphics:
  Device-1: Intel UHD Graphics 630 vendor: Hewlett-Packard driver: i915 
  v: kernel bus ID: 00:02.0 chip ID: 8086:3e92 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel UHD Graphics 630 (Coffeelake 3x8 GT2) 
  v: 4.5 Mesa 18.2.2 compat-v: 3.0 direct render: Yes 

**Additional context**
Was this something left out due to time/resource constraints, hard coding or will be revisited later?

**Comment by JosephMcc** [comment]
Which themes are you seeing this in? It seems to work ok here at least in Mint-Y.

**Comment by Harry-W-Haines-III** [comment]
Mint-X default desktop theme only.

**Comment by Harry-W-Haines-III** [comment]
Opps, sorry, that was the wrong one.  The default Linux Mint Desktop theme, to the right of Cinnamon.

**Comment by JosephMcc** [comment]
Ah, ok. This isn't a bug. The Linux Mint theme doesn't not adapt to color changes. We only offer that in a single color. To get different colors we would have to offer the theme in a bunch of different variations. If you want matching colors you need to use one of the proper variations from Mint-X or Y to match the color of your other themes.

Thank you for taking the time to report this.
