### ISSUE TITLE
Duplicate "Text Editor" entry in Mint menu (when installing gedit on top of the default xed) (fix included)

### ISSUE THREAD

**Issue by Butterfly1984** [linuxmint/mint-19.1-beta#42]
Describe the bug
Duplicate "Text Editor" entry in Mint menu

To Reproduce

    Install gedit text editor
    Go to 'Mint menu'
    Type in search bar 'text editor'
    See duplicate "text editor" entry (in English)

Expected behavior
Different name for both entries:

    Text editor xed
    Text editor gedit
    instead of:
    Text editor
    Text editor

Frequency
Does the issue happen:

 X Always
    

Edition (Desktop environment):
In which edition is this happening?

X Cinnamon Edition

Live or post-install:
Indicate if this is happening after the installation, or during the live session:

X Post-install

Screenshots
https://imgur.com/PtOU5x0

Locale:
LANG=en_US.UTF-8
LANGUAGE=en_US

Possible fix
Just rename as mentioned in "Expected Behavior"

**Comment by leigh123linux** [comment]
Include it on https://github.com/linuxmint/mint-19.1-beta/issues/41

**Comment by Butterfly1984** [comment]
#41 was fixed and closed i noticed
#42 was included in #41 but hasn't been fixed, since it's closed, could it be overlooked?

**Comment by leigh123linux** [comment]
@JosephMcc Any thoughts on this?
