### ISSUE TITLE
nemo: Nemo partially localized without cinnamon-l10n package

### ISSUE THREAD

**Issue by gm10** [linuxmint/mint-19.1-beta#45]
**Describe the bug**
Nemo is mostly un-localized at least when run on 19.1 MATE without `cinnamon-l10n` installed.

**To Reproduce**
1. `apt install nemo`
2. Set locale to non-English.
3. Re-log because it seems to ignore locale environment variables passed on the command line completely
4. Start nemo

**Expected behavior**
Full localization (where available, of course).

**Frequency**
Does the issue happen:
- [X] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [ ] Cinnamon Edition
- [X] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X] Post-install
- [ ] Live session

**Screenshots**
![](https://i.imgur.com/1XyTY6d.png)

That's caja in the background, properly localized, and nemo in the foreground, only some elements on the about screen localized, as well as the list of keyboard shortcuts in preferences, but that's about all.

**Locale:**
The screenshot is with everything set to `pt_BR.UTF-8`, also tried everything to `de_DE.UTF-8` with the same result.

**Additional context**
#43 might be related but I do not have the problem described there of the root locale not getting loaded. It is however as limited as the user locale.

**Comment by NikoKrause** [comment]
Have you [cinnamon-translations](https://github.com/linuxmint/cinnamon-translations/tree/master/po-export) installed? 
I think the package is called `cinnamon-l10n`.

**Comment by gm10** [comment]
@NikoKrause installing that fixes it. It's weird to keep the localization in a separate package but if you do you should either make it a depend (it's a recommend) or not use gettext when it's not installed, because that partially localized version when it's missing just isn't right.
