### ISSUE TITLE
cinnamon: time hint, it is not in the date format of my country

### ISSUE THREAD

**Issue by antrrax** [linuxmint/mint-19.1-beta#46]
**Describe the bug**
On the taskbar, when I mouse over the time it displays a hint. But in this hint, the date appears in full in the English standard [day of the week - month - day].
But in my country the pattern of writing dates is different from American.
In Brazil the normal is:
[day of the week] [day] [string 'de'] [month]
Sunday

**To Reproduce**
1. place the mouse pointer over the date in the taskbar.

**Expected behavior**
The mint should use my country's location pattern to display the date in full

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**
<a href="https://ibb.co/Gn7bF9N"><img src="https://i.ibb.co/2Wqf5SH/bug5.png" alt="bug5" border="0"></a>
**Locale:**
Paste the output of `locale`.
pt-BR utf-8

**Comment by NikoKrause** [comment]
This is localized. If you say that `pt_BR` uses a different pattern, this means that the translation is wrong.
Please create a suggestion here: https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon/pt/+translate?batch=10&show=all&search=%25A
Or get in touch with Tiago Santos, who seems to do a lot of `pt_BR` translations: https://launchpad.net/~tiagofsantos81
