### ISSUE TITLE
cinnamon: Grouped window list drag icon bug

### ISSUE THREAD

**Issue by chico3434** [linuxmint/mint-19.1-beta#47]
**Describe the bug**
Grouped window list moves to right when i drag a icon to it.

**To Reproduce**
1. Go to menu
2. Drag a icon to panel
3. The grouped window list will accept the icon but will move to the center of the panel

**Expected behavior**
The grouped windows list is expected to accept the icon and continue on the left

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**
before
![panel_before](https://user-images.githubusercontent.com/37938332/49699519-5ea20c80-fbb9-11e8-88ea-65857e1b684f.png)
after dragging icon of PhpStorm to panel
![panel_after](https://user-images.githubusercontent.com/37938332/49699523-682b7480-fbb9-11e8-84f8-74e21e4431ed.png)
**Locale:**
LANG=pt_BR.UTF-8
LANGUAGE=pt_BR:pt:en
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC="pt_BR.UTF-8"
LC_TIME="pt_BR.UTF-8"
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY="pt_BR.UTF-8"
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER="pt_BR.UTF-8"
LC_NAME="pt_BR.UTF-8"
LC_ADDRESS="pt_BR.UTF-8"
LC_TELEPHONE="pt_BR.UTF-8"
LC_MEASUREMENT="pt_BR.UTF-8"
LC_IDENTIFICATION="pt_BR.UTF-8"
LC_ALL=

**Drivers:**
Graphics:
  Device-1: Intel HD Graphics 530 vendor: ASRock driver: i915 v: kernel 
  bus ID: 00:02.0 chip ID: 8086:1912 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 530 (Skylake GT2) 
  v: 4.5 Mesa 18.0.5 compat-v: 3.0 direct render: Yes

**Comment by NikoKrause** [comment]
I can reproduce this issue. Fix should be easy. Thanks for pointing this out.
