### ISSUE TITLE
Cannot boot an edited Linux Mint 19.1 ISO

### ISSUE THREAD

**Issue by highoctane305** [linuxmint/mint-19.1-beta#48]
**Describe the bug**
With a UEFI install of Linux Mint 19.1 x64 Cinnamon beta installed in VirtualBox 5.2.22, I can no longer edit the ISO of the same OS and have that ISO boot successfully on a computer using UEFI.

Using Cubic 2018.11-44-release~201811241746~ubuntu18.04.1, create a new project and use the Linux Mint 19.1 x64 Cinnamon beta ISO. When the chroot environment opens, do not make any changes, click Next and allow an ISO to be created. Copy the ISO out of the VM to the host OS and then write the ISO to a USB memory stick with 'USB Image Writer' and attempt to boot it on a computer with UEFI. It should fail to boot.

However, it works when doing this with a UEFI install of Linux Mint 19.0 x64 Cinnamon (note version 19.0 and not 19.1), installed in VirtualBox. Again, using the same version of Cubic as before, edit the Linux Mint 19.1 x64 Cinnamon beta ISO. When the chroot environment opens, do not make any changes, click Next and allow an ISO to be created. Write this ISO to a USB memory stick with 'USB Image Writer' and attempt to boot it on a computer with UEFI. It should work as expected. Because this method does work for me, I can make edits to the ISO content by installing additional packages, install various support files that I might want etc.

Why can I successfully edit the Linux Mint 19.1 x64 Cinnamon beta ISO version when Linux Mint 19.0 is the host OS, but cannot when the host OS is Linux Mint 19.1?

**To Reproduce**
See above.

**Expected behavior**
The custom ISO should boot on a UEFI system

**Frequency**
Does the issue happen:
- [*] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [*] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition
Probably the other editions too, but I have not tested this.

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [*] Post-install
- [ ] Live session

**Screenshots**

**Locale:**
LANG=en_NZ.UTF-8
LANGUAGE=
LC_CTYPE="en_NZ.UTF-8"
LC_NUMERIC=en_NZ.UTF-8
LC_TIME=en_NZ.UTF-8
LC_COLLATE="en_NZ.UTF-8"
LC_MONETARY=en_NZ.UTF-8
LC_MESSAGES="en_NZ.UTF-8"
LC_PAPER=en_NZ.UTF-8
LC_NAME=en_NZ.UTF-8
LC_ADDRESS=en_NZ.UTF-8
LC_TELEPHONE=en_NZ.UTF-8
LC_MEASUREMENT=en_NZ.UTF-8
LC_IDENTIFICATION=en_NZ.UTF-8
LC_ALL=

**Drivers:**
N/A
**Crash report:**

''Stack trace''
N/A

''Dmesg''
N/A

**Additional context**

**Comment by clefebvre** [comment]
This is outside of the scope for this BETA and it's also an observation. The cause or source of the bug isn't identified.

What I can say though, and I hope it helps, is that I can't think of any changes on our side that could explain this. We're building ISOs the exact same way as before, even the grub and kernel versions are unchanged since the last release.
