### ISSUE TITLE
Wrong link to Input Methods within system settings

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/mint-19.1-beta#5]
**Describe the bug**
In system settings the selection of input methods leads to language settings.
If you choose input methods in the menu instead it works as it should.

**To Reproduce**
    Open system settings (right click in any bar)
    Choose "Input Methods"

**Frequency**
Does the issue happen:
[x] Always
[ ] Randomly

**Edition (Desktop environment):**
[x] Cinnamon Edition
[ ] MATE Edition
[ ] Xfce Edition

**Live or post-install:**
[?] Post-install
[x] Live session

**Drivers:**
?

**Comment by NikoKrause** [comment]
Fixed by https://github.com/linuxmint/Cinnamon/commit/9b88d8251d3a89def5c84953112d8414efba416f
