### ISSUE TITLE
cinnamon: Alt+F2 does not support pkexec

### ISSUE THREAD

**Issue by gm10** [linuxmint/mint-19.1-beta#52]
**Describe the bug**
Apparently `pkexec <command>` doesn't work in Cinnamon's Alt+F2 command line at least in LM19. If you stick pkexec into a script and run the script instead it works fine. 

Not being a Cinnamon user, I don't have a 19.1 Cinnamon at hand but would be good if someone could check if the issue remains in Cinnamon 4. 

It's working correctly in the other editions.

**Frequency**
Does the issue happen:
- [X] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [X] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X] Post-install
- [X] Live session

**Comment by smurphos** [comment]
It does remain in Cinnamon 4. That reminds me a menu launcher with the command pkexec nemo works fine, same launcher on the desktop nada.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/Cinnamon/commit/112f155d0a4490bbe96019abe7e921e7ad92f62d
