### ISSUE TITLE
Desktop launchers with pkexec <command> fail

### ISSUE THREAD

**Issue by smurphos** [linuxmint/mint-19.1-beta#53]
**Describe the bug**
Menu launchers with a command such as 'pkexec lightdm-settings' fail to launch if they are added as a desktop launcher. xsession-errors complains with a `Refusing to render service to dead parents.` error message

**To Reproduce**

Right click the login menu and select add to desktop.
Attempt to launch the login menu.
View the lack of results.
Check xsession-errors.

**Expected behavior**
The same launcher should work on the desktop, the menu, or from a panel.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**

**Locale:**
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
**Drivers:**
Paste the output of `inxi -Gxx`.
Graphics:  Card: Intel 2nd Generation Core Integrated Graphics Controller
           bus-ID: 00:02.0 chip-ID: 8086:0116
           Display Server: x11 (X.Org 1.19.6 )
           drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.03hz
           OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile
           version: 3.3 Mesa 18.0.5 (compat-v: 3.0) Direct Render: Yes

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**
Also affects commands such as `pkexec nemo`  & `pkexec mintsources`

Can be worked around by editing the desktop launcher command to be `sh -c "pkexec lightdm-settings"`

Previously reported - https://github.com/linuxmint/nemo/issues/1891

**Comment by clefebvre** [comment]
https://github.com/linuxmint/nemo/issues/1891
