### ISSUE TITLE
Cinnamon: Add to panel icons oversized

### ISSUE THREAD

**Issue by y2vlog** [linuxmint/mint-19.1-beta#54]
**Describe the bug**
"Add to panel" icons oversized in center of top panel when initially added.

**To Reproduce**
1. Add a panel at top of screen.
2. Change "Panel height" in "Panel settings" dialog to match bottom bar height (27 on 1920x1080 screen).
3. "Add to panel" any app.
4. Size of icon is oversized for panel (see screenshots).
5. Drag icon in panel to rearrange or not, and icon sizes correct themselves.

**Expected behavior**
Corrected icon size when initially added.

**Frequency**
Does the issue happen:
- [x ] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x ] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x ] Post-install
- [x ] Live session

**Screenshots**
![image](https://user-images.githubusercontent.com/29636152/49758659-712d4c00-fc74-11e8-920a-6d3858bceb42.png)
![image](https://user-images.githubusercontent.com/29636152/49758691-7f7b6800-fc74-11e8-9ee3-712a16d82b7c.png)
![image](https://user-images.githubusercontent.com/29636152/49758710-886c3980-fc74-11e8-9c83-4829d285cd49.png)

**Locale:**
en_US.UTF-8

**Drivers:**
Graphics:
  Device-1: Intel Iris Graphics 540 driver: i915 v: kernel bus ID: 00:02.0 
  chip ID: 8086:1926 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel Iris Graphics 540 (Skylake GT3e) 
  v: 4.5 Mesa 18.0.5 compat-v: 3.0 direct render: Yes 

**Crash report:**
N/A

**Additional context**
Mint-Y-Dark-Red Theme except Mint-X-Red icons (setup as reported)
![screenshot from 2018-12-10 12-21-12](https://user-images.githubusercontent.com/29636152/49759350-47752480-fc76-11e8-97da-a9e407830af7.png)
All Mint-Y-Dark-Red Theme, same problem
![screenshot from 2018-12-10 12-26-15](https://user-images.githubusercontent.com/29636152/49759680-311b9880-fc77-11e8-8a9c-fe712cb3dc27.png)

**Comment by clefebvre** [comment]
I can't reproduce this.. @jaszhix @NikoKrause ?

**Comment by NikoKrause** [comment]
I can't reproduce this either

**Comment by jaszhix** [comment]
Same.
