### ISSUE TITLE
Change i18n of mint-update on pt_BR

### ISSUE THREAD

**Issue by otavioschwanck** [linuxmint/mint-19.1-beta#56]
**Describe the bug**
The "Atualizar" and "Instalar Atualizações" are very similar and can confuse users.

The ideal is change "Atualizar" to "Buscar atualizações"

**To Reproduce**
1. Open mint-update.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [x] MATE Edition
- [x] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [ ] Post-install
- [ ] Live session

**Screenshots**
![image](https://user-images.githubusercontent.com/9551316/49823585-3526e380-fd67-11e8-82eb-7b083f76d265.png)

**Locale:**
pt-BR

**Comment by NikoKrause** [comment]
Please suggest your changes here: https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/pt_BR/+translate?batch=10&show=all&search=Refresh

**Comment by VaGNaroK** [comment]
otavioschwanck  I can solve this, I am part of the translation team. thank you for the warning.
