### ISSUE TITLE
xreader:  broken navigation inside epub files

### ISSUE THREAD

**Issue by morton-f** [linuxmint/mint-19.1-beta#57]
When opening the epub file only the first page is displayed. 
It is possible to move inside some epubs with extensive index only by clicking through index in sidebar.
Xreader is set as the default application for  epub format, and this stage the problem for  'double-clicking' users. Please consider suspending epub support as previous versions of xreader had epub issues as well. 

How to reproduce:
Download The Debian Administrator's Handbook and try to scroll:
https://debian-handbook.info/get/now/

PDF is working fine

Xreader version 2.0.2

**Comment by collinss** [comment]
I'm pretty sure this is actually pretty common for programs that open epubs, and I don't think it's a bug. You should be able to access every page by using the navigation buttons on the toolbar. I believe it's set up that way so it more closely resembles turning the pages of a book.

**Comment by morton-f** [comment]
It is impossible to read 8 of 10 commercial epubs  in xreader at all.
Please try debian-handbook.epub freely available at https://debian-handbook.info/get/now/
This book has extensive menu for navigation which is not available in _xreader_.
You can browse it continuously or navigate with index in _FBReader_ and _Bookworm_.
You can not browse or  read any page in xreader.

In context: Debian 9 blocks opening epub in the Document Viewer.

![bookworm](https://user-images.githubusercontent.com/24711203/49860245-217c8b00-fe02-11e8-9c17-558934a01fee.png)
![fbreader](https://user-images.githubusercontent.com/24711203/49860246-217c8b00-fe02-11e8-9664-20e1e93ddcff.png)
![xreader](https://user-images.githubusercontent.com/24711203/49860247-217c8b00-fe02-11e8-979b-8c44a25a48b4.png)

**Comment by leigh123linux** [comment]
This isn't a new issue, it's also present in atril (xreader was forked from atril).

Please file it  against xreader.

https://github.com/linuxmint/xreader/issues
