### ISSUE TITLE
Xfce Raleigh theme controls missing outlines

### ISSUE THREAD

**Issue by FredF18** [linuxmint/mint-19.1-beta#58]
This is an official reporting of the problem in the Mint forums: https://forums.linuxmint.com/viewtopic.php?f=57&t=274509&p=1532708

Borders around controls are not drawn in both Mint 19, and 19.1 beta. See screen shots in the above forum link.

This occurs in a fresh install of 19.1 in VirtualBox with all updates applied. 

Reproduce with these steps:
1. Open Settings --> Appearance --> Styles. Select the "Raleigh" theme.
2. Return to Settings and open "Desktop Settings" .
3. Observe the controls are missing borders. 

This always happens, and has been confirmed by at least one other use of the Mint forums.

I have only tested in the Xfce Edition.

This happens in both Live sessions and post-install.

Paste the output of `locale`:
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

Output of `inxi -Gxx`:
Graphics:
  Device-1: InnoTek Systemberatung VirtualBox Graphics Adapter 
  driver: vboxvideo v: 5.2.20 r125813 bus ID: 00:02.0 chip ID: 80ee:beef 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  alternate: vboxvideo resolution: 1552x1055~60Hz 
  OpenGL: renderer: llvmpipe (LLVM 6.0 256 bits) v: 3.3 Mesa 18.0.5 
  compat-v: 3.0 direct render: Yes 

Regards,
Fred

**Comment by gm10** [comment]
The Raleigh theme is the gtk2 default theme, it's not compatible with Mint's gtk3 desktop environments. There nothing to fix other than maybe filter it out from the tool that lets you select it I guess.
