### ISSUE TITLE
VirtualBox installation: contradictory error report about disk space

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-19.1-beta#59]
**Describe the bug**
When trying to install Mint 19.1 beta within VirtualBox (version 5.2), Mint's installer tells me: you need at least 10.7GB to install Mint, and you have only 10.7GB (_sic_).

**To Reproduce**
1. Set up a VirtualBox with the beta, using VirtualBox's default disk allocation settings.
2. Boot into the virtualised liveISO (which gave me a 'Cinnamon in software rendering mode' warning - perhaps I had the wrong Vbox settings).
3. Try to install Mint.

**Expected behavior**

I expected the install to work or at least to get an error message that made more sense.

**Frequency**

Retrying from within the same Virtualised Live ISO, without restarting the virtual environment, produced the same error. I tried to restart the VM to test again but - and this seems a bug in its own right - the VM would not restart (and I tried twice).

**Edition (Desktop environment):**
In which edition is this happening?
Cinnamon.

**Live or post-install:**
Live and *during* install.

**Screenshots**

![image](https://user-images.githubusercontent.com/9998846/49850360-19f2bd00-fdd5-11e8-88fc-089c15f8ee7d.png)

**Additional context**

When I gave the VM at 25GB preallocated disk, Mint installed.

Host PC: ThinkPad X1CG6 (running Mint 19.0 Cinnamon).

Also: it's unclear to me what the 'skip' button on the installer would do. What would it skip? The current part of the installation process? The installation slide-show?

Finally: even when Mint installed, the graphics were not right:

![image](https://user-images.githubusercontent.com/9998846/49851187-2fb5b180-fdd8-11e8-8295-2f6b02b2a983.png)

But perhaps I should file a different report for that.

**Comment by gm10** [comment]
That's very likely just a rounding issue and not worth looking into. Just increase the size of your virtual disk and it will install just fine.

**Comment by ghost** [comment]
I think it is worth looking into, because (1) it is a problem one gets with the VirtualBox _defaults_, (2) it's Mint's installer reporting something that, on the face of it, makes no sense. Thinking 'an experienced user will work out what is going on here' does not gel with Mint's attempt to be an easy-to-use version of Linux.

**Comment by gm10** [comment]
Fair enough. It's for Clem to decide, anyway. I don't see him modifying the error message but maybe you can talk him into reducing the required size a little to make it fit on VirtualBox's default, he's the one who raised the installer's minimum requirement to 10 GiB (=10.7 GB) in the first place.

**Comment by ghost** [comment]
There may be something else to be considered here, namely, that VirtualBox's default disc handling expands disk size as necessary, i.e. uses [dynamic disks](https://www.virtualbox.org/manual/ch05.html).

**Comment by clefebvre** [comment]
We require more than 10GB.

> 15GB of disk space (20GB recommended)

**Comment by clefebvre** [comment]
It's hard to know exactly how much the installation would require. It depends on different factors and it would vary as the ISO changes over time.

The error message is funny and a bit silly.

Just tested a Korean installation without codecs, I'm already at 7.1GB, leaving less than 3GB for extras, that's tight. I really don't think 10GB is a good idea, even if it fits. I'd rather have people annoyed during the installation and take measures to increase the space than letting them install the OS and be stuck without free space on their first day of usage.

**Comment by ghost** [comment]
> I'd rather have people annoyed during the installation and take measures to increase the space than letting them install the OS and be stuck without free space on their first day of usage.

- You write as if at present the installer gives (1) a clear message about insufficient space (2) if and only if there is insufficient space.

- Yet at present both 1 and 2 are false.

- For, with Virtual Box, (i) the installer gives an unclear (contradictory) message and (ii) it gives it when -  according to how VirtualBox's self-expanding disks are meant to work - there is enough space. _ii_ may be a VirtualBox bug but it may also be a problem with your installer. _i_ is definitely the installer's fault.

**Comment by DaveBlack** [comment]
On Dec. 11th I added an enhancement idea on vbox forums to increase the default GNU/Linux virtual disk size (for VirtualBox 6.x.x) from 10GB to 20GB, mentioning Mint 19.1 system requirements
