### ISSUE TITLE
Please consider adding pdf to the 'Preferred Applications' list

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-19.1-beta#60]
**Describe the bug**

There are multiple PDF readers for Linux, including one shipped by Mint (and Adobe Reader runs under Wine, too). Yet, there is no PDF entry in the 'Preferred Applications' list.

**Expected behavior**
A PDF entry.

**Frequency**
Does the issue happen:
- [X] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [X] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [ ] Post-install
- [X] Live session

**Screenshots**

![image](https://user-images.githubusercontent.com/9998846/49852250-81137000-fddb-11e8-95df-e2a9ed4e5f3e.png)

**Additional context**
I feel that if you can add a Preferred Application for (even!) calculators, you can add one for PDF. (The separate entry for 'source code' - that's a nice one, too.)

Cf. [this Reddit post](https://forums.linuxmint.com/viewtopic.php?t=189408).
Cf. also [this report of a bug](http://kernelreloaded.com/linux-mint-sets-up-wrong-default-pdf-viewer-and-folder-launchers/), to do with Mint, PDF and Firefox (though ironically - or aptly - enough, Firefox on Mint would not open the link and I have to use a Chromium-based browser). I myself filed a bug against Firefox about that matter - the matter being that on Mint Firefox does not respect the default (but not sent in Preferred Applications . .) PDF reader; on my system, PDFs downloaded via Firefox open in . . Adobe Reader, under Wine.

**Comment by leigh123linux** [comment]
File this as a feature request for cinnamon as it's not a beta issue!!
