### ISSUE TITLE
Virtual Box: cannot escape software-rendering mode

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-19.1-beta#61]
**Describe the bug**
Cinnamon is stuck in software-rendering mode, on VirtualBox.

**To Reproduce**
1. Install the beta from within VirtualBox.
2. Reboot, install updates, reboot.

**Expected behavior**

**Frequency**
Does the issue happen:
- [X] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [X] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X] Post-install
- [X] Live session

**Screenshots**
![image](https://user-images.githubusercontent.com/9998846/49852713-cedca800-fddc-11e8-8839-1bf39df73324.png)

**Locale:**
Text pasting from the VM isn't working, for some reason, so:
![image](https://user-images.githubusercontent.com/9998846/49853261-7c03f000-fdde-11e8-8723-8e94b2df1c4b.png)

**Drivers:**
Paste the output of `inxi -Gxx`.
![image](https://user-images.githubusercontent.com/9998846/49853222-6098e500-fdde-11e8-9094-f5332f469b19.png)

**Additional context**

Host OS: Mint 19.0 x64 Cinnamon.
Host PC: Lenovo ThinkPad X1CG6.
Virtual Box 5.2, with: 6GB RAM allocated to main memory; the graphics memory slider pushed as far as it will go; 3d graphics acceleration enabled (and/but VBox will not allow me to enabled _2d_ acceleration).

I rebooted, installed a lot of updates, rebooted again - all to no avail. Also, the Driver Manager offers several options (see screenshot below), but I got nowhere with them. One combination of those settings made the Mint logo (in the wallpaper) a bleached yellow; and trying to enable another combination generated an error message about missing dependencies.

![image](https://user-images.githubusercontent.com/9998846/49853012-b9b44900-fddd-11e8-98de-d11260f8a917.png)

**Comment by gm10** [comment]
You need to install the guest additions via the Virtualbox menu. Note that v5.2.22 additions are bugged. Also this is about bug reports with the Mint 19.1 beta, not third-party software.

**Comment by smurphos** [comment]
Not a Cinnamon bug. The Vbox 5.2.22 Guest Additions have got a bug that incorrectly disables 3D acceleration. They went a bit far trying to fix another bug...

Solutions https://forums.linuxmint.com/viewtopic.php?f=231&t=283079#p1562690

https://www.virtualbox.org/ticket/18116

**Comment by ghost** [comment]
I had forgotten about VBox fiddles (the guest additions) and did not know of the bug. _Mentioning those things in the Mint 19.1 release notes would be an idea._ (Theres also the fact that Firefox is failing to download the beta ISOs and indeed the VBox editions, though another browser can - but perhaps that problem is my end and at any rate it is not a Mint problem.)
