### ISSUE TITLE
Update Manager makes no mention of mirrors

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-19.1-beta#62]
**Describe the bug**
Mirrors are mentioned nowhere in the Update Manager nor even in its help file. It's not obvious that Software Sources is the place to go to choose mirrors.

**To Reproduce**
1. Open the Update Manager.
2. Wonder about mirrors.
3. Try and fail to find mention of mirrors in the application or in the helpfile.
4. Eventually think of trying Software Sources.

**Expected behavior**
Getting to - or at least getting information about mirrors - should be possible from within the Update Manager.

**Frequency**
Does the issue happen:
- [X] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [X] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X] Post-install
- [ ] Live session

**Additional context**
I discover that Mint 19.0 has the same problem. The problem is cosmetic in a sense, yet it may throw new users - or even old ones who are suprised to receive no prompt about mirrors and forget that Software Sources handles mirrors.

**Comment by gm10** [comment]
When it suggests to switch to a local mirror the [OK] button takes you directly to Software Sources, so there's not much room left for wondering how to get there, is there?

Agreed on the help file, but it's missing a lot of info.

**Comment by ghost** [comment]
Yes: *when* - if - it suggests . . Still, I suppose if it sees no need to make one change mirror, then it is not urgent that one be able to find the mirror settings.

It seem to me that it would be a good idea for the Update Manager to have a menu option entitled 'Software Sources (for mirrors and more)' - or have the parenthetical text as a tooltip.

**Comment by gm10** [comment]
If it doesn't suggest to switch mirrors then why would you even be wondering about the term "mirrors"? I don't feel anything needs or even should be changed in the GUI here so I'll stay out of it, but maybe the Mint dev team will follow your point of view.

**Comment by clefebvre** [comment]
No, I really don't see a problem here either.

First, assuming you're a novice user, why would the term "mirror" speak to you more than "software source"? If I ask my mom, I'm pretty sure she'll get a better idea of what a source is, than a mirror.

Second, unless you actually tell the manager to stop telling you, or you choose a mirror, it WILL ALWAYS tell you to choose one, and bring you to the right place. The minute it's finished bugging you about timeshift, it'll bug you about that.
