### ISSUE TITLE
Cinnamon start menu Favorites don't expand to accommodate added icons.

### ISSUE THREAD

**Issue by plong1** [linuxmint/mint-19.1-beta#63]
When adding apps to the favorites bar in the Mint start menu, it seem that you are limited to display only 5 or 6 icons . Any more than that and menu won't resize to show them.

**Comment by plong1** [comment]
The time/date applet in Cinnamon doesn't resize with the other applets like it does in version 19.

**Comment by smurphos** [comment]
It's a scroll box now, try mouse wheel scrolling over the favourite box or hovering near the top or bottom.

**Comment by plong1** [comment]
Ok thank you for your quick response. I must say im not a big fan of the
idea of scrolling, but thats just me. Someone else may really like it. To
me if you have to take the extra step to scroll, you might as well just
navigate the menu to find what you need. You cant please everyone i guess.
Thanks again.

**Comment by clefebvre** [comment]
There's a configuration option for it too:

![image](https://user-images.githubusercontent.com/1138515/49871788-0d8b5600-fe0f-11e8-99b7-a00e16ce7e42.png)

**Comment by plong1** [comment]
Whoa! That's awesome! Thanks!
