### ISSUE TITLE
mintupdate: "Hide after applying updates" option is broken

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/mint-19.1-beta#65]
**Describe the bug**
There's an option in mintupdates settings called "Hide after applying updates", which seems to be broken

**To Reproduce**
1. Check the option "Hide after applying updates"
2. Apply some updates
3. mintupdate doesn't close after the updates are applied and you have to click the "Close" button

**Expected behavior**
I'd expect mintupdate to be closed after the updates are finished

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [x] MATE Edition
- [x] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Additional context**
This option works fine in Mint 18.3

**Comment by gm10** [comment]
@NikoKrause we had already talked about it on slack, didn't we? Fix is pending here: https://github.com/linuxmint/mintupdate/pull/430  for after 19.1

**Comment by NikoKrause** [comment]
Yeah, I wanted it to get into 19.1 ;)

**Comment by gm10** [comment]
Not my decision, of course, I'd have liked both of my "Fix" prefixed PRs in at least, plus ideally the blacklist feature, since it's tiny.
