### ISSUE TITLE
Desktop 'customise' menu: two suggestions to make it more usable

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-19.1-beta#66]
**Describe the bug**
(1) **The menu item 'customise'** (that one sees when one right-clicks the desktop) _could be more descriptive_. 'Customise _what_?', the user wonders. How about 'customise desktop'?

(2) **The slider**: _initially I deemed the slider a visual artefact_, a bug - partly because, due to the slider and to the way the vertical dots and horizontal dots meet, the impression is somewhat that of one window overlaying another. I suggest: (i) putting more of a space between the sets of dots and (ii) labeling the slider. As an alternative or addition to _i_, the slider groove could be made greyer (rather than the current black or near-black). EDIT: Although, OK - and about labelling - there is a tooltip - that's good.

![image](https://user-images.githubusercontent.com/9998846/49890087-1d209400-fe3b-11e8-8089-55b7297f1420.png)

Users would get used to the window quickly enough; but it seems to me that, where it is fairly easy to create instant comprehension, so doing is desirable.

**Edition (Desktop environment):**
In which edition is this happening?
- [X] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X] Post-install
- [ ] Live session

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
