### ISSUE TITLE
Caja does not resize desktop area after automatic resolution change

### ISSUE THREAD

**Issue by jsane-h8ms** [linuxmint/mint-19.1-beta#70]
**Describe the bug**
My setup:
Laptop with 2880x1620 display
Docking station with 1920x1080 (or 1200) monitor connected
![bug](https://user-images.githubusercontent.com/40062334/49945873-1868e800-feee-11e8-9c0a-d9479628d02e.png)

When docked, both displays use 1920x1080, for a total usable desktop size of 3840x1080.
The resolution of my laptop display is automatically adjusted when docking or undocking (as it should), but the usable desktop area does not change with the resolution.

When docking for example, the added screen area to the right is usable for applications, but the desktop wallpaper is not redrawn, causing visual artifacts and I can not place desktop items there or drag a selection box with my mouse. (See screenshot and illustration, blue criss-crossed area is broken)
![screen](https://user-images.githubusercontent.com/40062334/49945883-1d2d9c00-feee-11e8-8219-1ce09bc2da9f.png)

The same happens when undocking, (if the session was started docked) the added desktop area below is not usable (green area in illustration; in this case, the visual artifacts do not happen most of the time).

This is a regression from 18.1 (Mate GTK2 build; I skipped 18.2 and 18.3 with GTK 3 because of theming issues, so did not test).

**To Reproduce**
1. Get high-dpi laptop, dock and 1080p monitor
2. dock laptop
3. Adjust laptop resolution to 1080p
4. undock laptop
5. if neccessary, adjust laptop resolution back to native
6. reboot
7. dock laptop, wait for resolution change
8. observe artifacts

**Expected behavior**
Caja notices the new display resolution(s) and adjusts desktop area accordingly.

**Frequency**
Happens almost always.

**Edition (Desktop environment):**
MATE 1.20

**Live or post-install:**
Post-install

**Screenshots**
See above

**Drivers:**
Graphics:
  Device-1: Intel 4th Gen Core Processor Integrated Graphics vendor: Lenovo 
  driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0416 
  Device-2: NVIDIA GK208M [GeForce GT 730M] vendor: Lenovo driver: nouveau 
  v: kernel bus ID: 01:00.0 chip ID: 10de:1290 
  Display: x11 server: X.Org 1.19.6 driver: modesetting,nouveau 
  unloaded: fbdev,vesa compositor: marco resolution: 1920x1200~60Hz 
  OpenGL: renderer: Mesa DRI Intel Haswell Mobile v: 4.5 Mesa 18.0.5 
  compat-v: 3.0 direct render: Yes

''Dmesg''
Nothing related as far as I can tell.

**Comment by clefebvre** [comment]
Hi @hate-m-dollarsign, please post this issue against Caja directly: https://github.com/mate-desktop/caja/issues
