### ISSUE TITLE
Colored folders inside Nemo are presented at a lower resolution

### ISSUE THREAD

**Issue by BrunoNZ** [linuxmint/mint-19.1-beta#71]
**Describe the bug**
After changing the color of a folder, inside Nemo, this folder is presented at a resolution much lower than the original one.

**To Reproduce**
1. Go to 'Nemo'
2. Right-Click on a folder and select a new color
3. See error. Increase zoom to see it clearer.

**Expected behavior**
To show an icon with the same resolution as the original but in the selected color.

**Frequency**
Does the issue happen:
- [X] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X] Post-install
- [ ] Live session

**Comment by otavioschwanck** [comment]
I can confirm.
![image](https://user-images.githubusercontent.com/9551316/49958883-3f75e880-fef3-11e8-9700-24205c2e7d6a.png)

**Comment by clefebvre** [comment]
Confirmed, they're using pngs as opposed to svgs. Not a release blocker but I'll add this to the roadmap.
