### ISSUE TITLE
Xreader: text remains (as it was in Mint 19.0) unselectable

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-19.1-beta#77]
**Describe the bug**
Text is not selectable with click and drag.

**To Reproduce**

Please see [extant bug report for Mint 19](https://github.com/linuxmint/xreader/issues/95). So: this is not a regression, but it is the persistence of what seems to be a rather serious brokenness.

**Frequency**
Does the issue happen:
- [X] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [X] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X] Post-install
- [ ] Live session

**Locale:**
```
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

**Drivers:**
Graphics:
  Device-1: InnoTek Systemberatung VirtualBox Graphics Adapter 
  driver: vboxvideo v: 5.2.23 r127298 bus ID: 00:02.0 chip ID: 80ee:beef 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  alternate: vboxvideo resolution: 1920x1120~60Hz 
  OpenGL: renderer: Chromium v: 2.1 Chromium 1.9 direct render: Yes 

**Additional context**

I attach the PDF with which I tested. I would have tested with more files, were it not that getting PDFs into VirtualBox, especially on my Windows VirtualBox (where drag and drop and file sharing seems broken), proved excessively hard.
[TweakHoundTweakingWindows8_1.pdf](https://github.com/linuxmint/mint-19.1-beta/files/2682607/TweakHoundTweakingWindows8_1.pdf)

**Comment by otavioschwanck** [comment]
Here i can.
![image](https://user-images.githubusercontent.com/9551316/50043128-e4a8d200-0055-11e9-8acf-e082c5e08d7b.png)

Vídeo with demonstration:
https://www.dropbox.com/s/khe88nstl2ozzfn/selectingropriedades.mkv?dl=0

LANG=pt_BR
Drivers:
Graphics:
  Device-1: Intel HD Graphics 5500 vendor: Dell driver: i915 v: kernel 
  bus ID: 00:02.0 chip ID: 8086:1616 
  Device-2: AMD Topaz XT [Radeon R7 M260/M265 / M340/M360 / M440/M445] 
  driver: amdgpu v: kernel bus ID: 04:00.0 chip ID: 1002:6900 
  Display: x11 server: X.Org 1.19.6 driver: amdgpu,ati,modesetting 
  unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 5500 (Broadwell GT2) 
  v: 4.5 Mesa 18.0.5 compat-v: 3.0 direct render: Yes

**Comment by ghost** [comment]
@otavioschwanck

Well, that's good! Does it work with a range of PDF files? Also: Mint 19 or Mint 19.1?

**Comment by clefebvre** [comment]
Tracked at https://github.com/linuxmint/xreader/issues/95

**Comment by clefebvre** [comment]
It works for me too, full-screen or normal with the PDF you provided.
I can't select in presentation mode (F5) but that's by design afaik.

**Comment by clefebvre** [comment]
In any case, there's no need to duplicate issues already reported. This isn't a blocker.

**Comment by otavioschwanck** [comment]
> @otavioschwanck
> 
> Well, that's good! Does it work with a range of PDF files? Also: Mint 19 or Mint 19.1?

19.1

**Comment by gm10** [comment]
@otavioschwanck it's a HiDPI issue only, xreader scales its overlay when it shouldn't, because the content doesn't get scaled.
