### ISSUE TITLE
Cinnamon: Update Manager (panel icon) tool-tip contains extra blank lines

### ISSUE THREAD

**Issue by DaveBlack** [linuxmint/mint-19.1-beta#82]
**Describe the bug**
Update Manager (panel icon) tool-tip, ‘Could not refresh the list of updates’ contains extra blank lines compared tool-tips for other panel icons. In comparison, 'Your system is up to date' appears with correct sizing.

**To Reproduce**
1. After disconnected from Internet, and Update Manager icon changes to red X
2. Hover mouse over Update Manager icon for status update

**Expected behavior**
Tool-tip height sizing should be consistent for all states

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**
![update manager panel icon tool-tip extra blank lines](https://user-images.githubusercontent.com/13056699/50046532-c6b29000-009c-11e9-817c-03bcb339f1c5.png)

**Locale:**
 LANG=en_GB.UTF-8

**Drivers:**
 NVIDIA 390.77

**Comment by clefebvre** [comment]
I think it's trying to show an error message here...

**Comment by gm10** [comment]
I'll add a quick fix because why not...  (by removing the lines, not by adding an error message)

edit: There you go:
