### ISSUE TITLE
Cinnamon: Toggling 'Traditional' / 'Modern' leaves 'User' applet

### ISSUE THREAD

**Issue by DaveBlack** [linuxmint/mint-19.1-beta#84]
**Describe the bug**
Minor issue. Toggling 'Traditional' / 'Modern' leaves 'User' applet 

**To Reproduce**
1. Preferences -> Welcome screen -> First Steps 
2. Switch to 'Traditional', then back to 'Modern'
3. User applet isn't removed

**Expected behavior**
User applet should be removed after switching to honour the new Modern default panel layout

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session (untested)

**Locale:**
 LANG=en_GB.UTF-8

**Drivers:**
 NVIDIA 390.77

**Comment by clefebvre** [comment]
I noticed that during QA :)
