### ISSUE TITLE
Update Manager: Discrepancy in kernel version and changelog between list of updates and Kernels dialog

### ISSUE THREAD

**Issue by mattvalley** [linuxmint/mint-19.1-beta#86]
**Describe the bug**
In the Update Manager, the main list of available updates shows a version of 4.15.0.42.44.  When I click the Changelog link for the 4.15.0-42 kernel in the Kernels dialog, it loads the page in firefox for the 4.15.0-42.45 version.  The last part of the version number is different.  Also the changelog output is different between the two.  Together these make it appear that the Kernels dialog and the main list of available updates are out of sync.

**To Reproduce**
1. After a fresh install, make sure to apply all of the package updates with this command in the terminal: sudo apt-get update; sudo apt-get upgrade -y; sudo apt-get dist-upgrade -y;
2. Restart the system and log back in
3. Launch the Update Manager app and wait for the list of updates to refresh.
4. Notice the available kernel update has a version of 4.15.0.42.44.
5. Select that update and click the Changelog tab at the bottom.
6. Take note of the output for the changelog.
7. Don't install the update yet.
8. Click the View menu item and select the "Linux kernels" option.
9. Click the Continue button if needed to go to the list of kernels.
10. Select the 4.15.0-42 kernel at the top and click the Changelog link
11. When firefox loads the page, notice that the version is slightly different with the last number being 45 instead of 44.  Also notice that the changelog output is very different than the previous output.

**Expected behavior**
Overall I expected the version number and the changelog output to be identical between the various places they are provided so that the user experience of viewing and choosing a kernel update to apply is consistent.

I realize the changelog website might be providing more level of detail than the tab in the Update Manager, but I expected at least the versions to be the same.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**
Screenshot of the list of updates:
![kernel_version_update_list](https://user-images.githubusercontent.com/4983376/50047107-758aa800-006c-11e9-8487-bc87be5e98fe.png)

Screenshot of the changelog website:
![kernel_version_kernel_list](https://user-images.githubusercontent.com/4983376/50047111-81766a00-006c-11e9-9271-52e2e1358238.png)

**Locale:**
Paste the output of `locale`.
```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
**Drivers:**
Paste the output of `inxi -Gxx`.
```
Graphics:  Device-1: InnoTek Systemberatung VirtualBox Graphics Adapter driver: vboxvideo v: kernel bus ID: 00:02.0 
           chip ID: 80ee:beef 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa alternate: vboxvideo 
           resolution: 1920x1007~60Hz 
           OpenGL: renderer: llvmpipe (LLVM 6.0 256 bits) v: 3.3 Mesa 18.0.5 compat-v: 3.0 direct render: Yes 
```

**Comment by gm10** [comment]
Not a bug. Kernel versioning is done upstream by Ubuntu, as are the changelogs.

There  are various issues surrounding changelog display in Update Manager that could be improved. I've got a solution for that but it won't be available in 19.1 and may not ever be (not up to me).
