### ISSUE TITLE
Update Manager: Installing a new kernel version in the Kernels dialog does not install everything

### ISSUE THREAD

**Issue by mattvalley** [linuxmint/mint-19.1-beta#87]
**Describe the bug**
When I use the Kernels dialog to install a new kernel version and then the system is restarted, the Update Manager still shows it as an available update that needs to install more packages.  As a result it appears that using the Kernels dialog did not install everything in order to complete the process of installing a new kernel version.

**To Reproduce**
1. After a fresh install, make sure to apply all of the package updates with this command in the terminal: sudo apt-get update; sudo apt-get upgrade -y; sudo apt-get dist-upgrade -y;
2. Restart the system and log back in
3. Launch the Update Manager app and wait for the list of updates to refresh
4. Notice there is an available kernel update for 4.15.0.42.44.
5. Instead of installing that update here, we will install it with the Kernels dialog...
6. Click the View menu item and select the "Linux kernels" option
7. Click the Continue button if needed to go to the list of kernels
8. Select the 4.15.0-42 kernel at the top and click the Install button
9. Click Yes in the prompt to confirm the installation
10. Enter the user password to continue
11. Once the Applying Changes dialog is finished, restart the system and log back in
12. Launch the Updates Manager app
13. Click the Refresh button to regenerate the list of available updates
14. Notice that the kernel update we previously saw is still there
15. Select that update and click the Install Updates button
16. Notice the prompt which states that additional packages such as linux-headers-generic and linux-image-generic need to be installed.

**Expected behavior**
My expectation was that installing the new kernel version using the Kernels dialog would be equivalent to installing it using the list of available updates.  Thus if I install a new kernel version with the Kernels dialog I would have nothing left to do and that the system would be fully switched over to using the new kernel version.  But when I still see the same kernel version as an available update after restarting the system and when I see that even more packages need to be installed, it makes me think that the installation from the Kernels dialog was incomplete or that it didn't work correctly (even though there were no errors).

I'm not sure if this is an actual bug or a training issue where the Kernels dialog just needs to provide better helper text to explain to users what it is doing and what steps users should normally follow to install new kernel versions.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Locale:**
Paste the output of `locale`.
```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
**Drivers:**
Paste the output of `inxi -Gxx`.
```
Graphics:  Device-1: InnoTek Systemberatung VirtualBox Graphics Adapter driver: vboxvideo v: kernel bus ID: 00:02.0 
           chip ID: 80ee:beef 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa alternate: vboxvideo 
           resolution: 1920x1007~60Hz 
           OpenGL: renderer: llvmpipe (LLVM 6.0 256 bits) v: 3.3 Mesa 18.0.5 compat-v: 3.0 direct render: Yes 
```

**Comment by gm10** [comment]
Working as intended. The kernel window is for manually installing a non-default kernel version that won't be kept up to date. It won't touch the kernel meta package, which is what the updater uses to keep you up to date.
