### ISSUE TITLE
Nvidia drivers won't run

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-19.1-beta#88]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**

**Locale:**
Paste the output of `locale`.

**Drivers:**
Paste the output of `inxi -Gxx`.

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**

**Comment by ghost** [comment]
The Driver Manager installed the latest Nvidia drivers for 1070 Ti cards but runs in rendering mode. Blacklisted nouveau driver, rebooted & reinstalled Nvidia 415.23.
As I recall in Linux Mint 19 I installed the Nvidia 415.23 drivers first thing after installing Mint & rebooted. Nouveau nor rendering mode did not occur.

**Comment by leigh123linux** [comment]
Insufficient info provided, try using the template next time and provide logging.

**Comment by ghost** [comment]
After replacing Linux Mint 19.1 with 19 I think I may have spotted the cause of the problem. This Asus MB has something called Secure Boot turned on. When I get to the bizarre page that asks if I want to install third-party software it says I have to enter a key code. With 19.1 I entered a 7 digit word and it said Short Password but it displayed a working Continue button, which I clicked, and it let me complete the installation. With 19 it said Short Password and left the Continue button grayed out and I had to use a stronger pw before it let me install it.
BTW, Nvidia makes the GPU and writes the drivers for their GPUs. That makes them first-person software NOT third-person. Third-person would be NOT Nvidia & NOT Linux but other.
