### ISSUE TITLE
cinnamon: GWL - Panel pinned icons rearrangement not honoured

### ISSUE THREAD

**Issue by DaveBlack** [linuxmint/mint-19.1-beta#9]
**Describe the bug**
Pinned icons rearrangement not honoured, every time Cinnamon is restarted, logout / system restart, icons return to locations appeared when added to panel.

**To Reproduce**
1. Using Menu add extra icons to panel
2. Rearrange icons
3. Restart Cinnamon, logout / system restart

**Expected behaviour**
Pinned icons rearrangement should remain

**Frequency**
Does the issue happen:
[x] Always
[ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
[x] Cinnamon Edition
[ ] MATE Edition
[ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
[x] Post-install
[x] Live session

**Locale:**
LANG=en_GB.UTF-8

**Drivers:**
NVIDIA 390.77

**Additional context**
Until fixed, custom arrangement can be achieved by manually editing 3.json text file (jump to line 172).

`xed .cinnamon/configs/grouped-window-list@cinnamon.org/3.json`

**Please note: each icon entry (except for the last) must end with a comma!**

**Comment by NikoKrause** [comment]
Can you try the option `Pin apps when dragged to a new position` in the settings of the grouped window list? The option is at the very bottom of the `Panel` page in the settings.

**Comment by DaveBlack** [comment]
Thanks, wouldn't have considered that option. With ITM, icons can be rearranged whether that option is enabled / disabled.

Would you like me to generate a PR to change the default (already made a fork and changed the setting)? Or would you prefer to discover why ITM works with / without this option enabled?

**Comment by jaszhix** [comment]
This was a default we discussed and decided to disable by default because its closer to the behavior of the original window list applet.

**Comment by DaveBlack** [comment]
Thanks for your reply, and excellent work on ITM and GWL.

App rearrangement is an expected default behaviour on many popular OS, unless a lock setting has been explicitly set.

Should GWL replicate original window list applet, since intended to be a fresh new 'Modern' experience?
